
export const GET_IMAGES_REQUEST = 'GET_IMAGES_REQUEST';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_FAIL = 'GET_IMAGES_FAIL';

export const RESET_IMAGES_REQUEST = 'RESET_IMAGES_REQUEST';
export const RESET_IMAGES_SUCCESS = 'RESET_IMAGES_SUCCESS';
export const RESET_IMAGES_FAIL = 'RESET_IMAGES_FAIL';
